/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus2;
import org.postgresql.ds.PGSimpleDataSource;
import org.postgresql.Driver;
import java.sql.*;
public class App {
    public static void main(String[] args) {
        PGSimpleDataSource ds = new PGSimpleDataSource();
        ds.setServerName("localhost");
        ds.setPortNumber(26257);
        ds.setDatabaseName("nf");
        ds.setUser("root");
        ds.setPassword(null);
        //ds.setSsl(true);
        // ds.setSslMode("require");
        // ds.setSslCert("certs/client.admin.crt");
        // ds.setSslKey("certs/client.admin.key.pk8");
        ds.setReWriteBatchedInserts(true); // add `rewriteBatchedInserts=true` to pg connection string
        ds.setApplicationName("Kasus");
        try (Connection conn=ds.getConnection()) {
            
        } catch (Exception e) {
            //TODO: handle exception
        }
        
    }
}
